changelog:
  categories:
    - title: Breaking Changes 🛠
        - Semver-Major        
    - title: New Content 🎉
      labels:
        - content
    - title: New Features
      labels: 
        - Semver-Minor
      exclude:
        - content
    - title: Other Changes
      labels:
        - "*"
