name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest

      - name: Upload with comment
        run: |
          echo "## Screenshots" > report.md
          cml-publish main-site/e2e/screenshots/*.png --md >> report.md
          cml-send-comment report.md
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install -r requirements.txt
      - run: python -m ruff check
